# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ed2d50b3a29697af7360b72762d758b"
name = "Edge Timer"
application_url = "https://urgency-timer.onrender.com"
embedded = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_own_subscription_contracts,write_own_subscription_contracts,write_products"

[auth]
redirect_urls = [ "https://urgency-timer.onrender.com/auth" ]

[app_proxy]
url = "https://urgency-timer.onrender.com/proxy"
subpath = "urgency-timer"
prefix = "apps"
